In [5]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
df = pd.read_csv('C:\\Users\\aviji\\Desktop\\capstone_project_1\\olist_order_items_dataset.csv')

In [6]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [7]:
df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [8]:
cols = ['shipping_limit_date']

for c in cols:
    df[c] = df[c].astype('datetime64[ns]')

In [9]:
print("duplicated_rows:", df.duplicated().sum())

dup_rows = df[df.duplicated()]

print(dup_rows.head())

duplicated_rows: 0
Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [10]:
df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [11]:
df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')

In [12]:
print("price <= 0:", (df['price'] <= 0).sum())
print("freight < 0:", (df['freight_value'] < 0).sum())
# show examples
print(df[df['price'] <= 0].head())
print(df[df['freight_value'] < 0].head())

price <= 0: 0
freight < 0: 0
Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []
Empty DataFrame
Columns: [order_id, order_item_id, product_id, seller_id, shipping_limit_date, price, freight_value]
Index: []

In [13]:
cols = ['order_id','order_item_id','product_id','seller_id','price','freight_value','shipping_limit_date']
print(df[cols].isna().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
price                  0
freight_value          0
shipping_limit_date    0
dtype: int64

In [14]:
susp = df[df['freight_value'] > df['price']]
print("freight > price count:", len(susp))
print(susp.sample(5))

freight > price count: 4119
                                order_id  order_item_id  \
12148   1b90587d2255b7eb1dcc4d2c7eba1c54              1
80827   b7c91c3a97f9089e9b438320b5b34f37              3
111059  fc54a67aa2c88278d6475185217dc47d              1
24186   371dcdd114490b436dff8fac7d52a928              1
61566   8c6a3fab1ed272b02f23bb7dc9061d9a              1

                              product_id                         seller_id  \
12148   75c06ee06b201f9b6301d2b5e72993f8  3c7c4a49ec3c6550809089c6a2ca9370
80827   b756577e274d3a4793fc27209d7072db  11bfa66332777660bd0640ee84d47006
111059  67bd616e1ba0d3d3e8545f3113b0140d  e9779976487b77c6d4ac45f75ec7afe9
24186   716b606a119bc544bbda57aa94853f0d  7681ef142fd2c19048da7430856b5588
61566   8d12ee985749e3ea570ed7f5c875479a  d91fb3b7d041e83b64a00a3edfb37e4f

       shipping_limit_date  price  freight_value
12148  2018-01-25 02:38:48  13.99          14.10
80827  2017-12-12 22:49:39  10.99          25.63
111059 2018-05-07 05:30:54  14.49          18.23
24186  2018-07-05 02:53:27  60.00          60.03
61566  2018-04-19 02:30:47  14.30          18.23

In [15]:
print("min order_item_id:", df['order_item_id'].min(), "max:", df['order_item_id'].max())
items_per_order = df.groupby('order_id')['order_item_id'].nunique()
print("orders with >10 items:", (items_per_order>10).sum())
print(items_per_order.describe())

min order_item_id: 1 max: 21
orders with >10 items: 17
count    98666.000000
mean         1.141731
std          0.538452
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
Name: order_item_id, dtype: float64

In [16]:
(df['price'] <= 0).sum()

np.int64(0)

In [17]:
(df['freight_value'] < 0).sum()

np.int64(0)

In [18]:
df['item_total'] = df['price'] + df['freight_value']

In [19]:
df.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'item_total'],
      dtype='object')

In [20]:
df.nlargest(10, 'item_total')

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total
3556,0812eb902a67711a1cb742b3cdaa65ae,1,489ae2aa008f021502940f251d4cce7f,e3b4998c7a498169dc7bce44e6bb6277,2017-02-16 20:37:36,6735.00,194.31,6929.31
112233,fefacc66af859508bf1a7934eab1e97f,1,69c590f7ffc7bf8db97190b6cb6ed62e,80ceebb4ee9b31afb6c6a916a574a1e2,2018-08-02 04:05:13,6729.00,193.21,6922.21
107841,f5136e38d1a14a4dbd87dff67da82701,1,1bdf5e6731585cf01aa8169c7028d6ad,ee27a8f15b1dded4d213a468ba4eb391,2017-06-15 02:45:17,6499.00,227.66,6726.66
74336,a96610ab360d42a2e5335a3998b4718a,1,a6492cc69376c469ab6f61d8f44de961,59417c56835dd8e2e72f91f809cd4092,2017-04-18 13:25:18,4799.00,151.34,4950.34
11249,199af31afc78c699f0dbf71fb178d4d4,1,c3ed642d592594bb648ff4a04cee2747,59417c56835dd8e2e72f91f809cd4092,2017-05-09 15:50:15,4690.00,74.34,4764.34
62086,8dbc85d1447242f3b127dda390d56e19,1,259037a6a41845e455183f89c5035f18,c72de06d72748d1a0dfb2125be43ba63,2018-06-28 12:36:36,4590.00,91.78,4681.78
29193,426a9742b533fc6fed17d1fd6d143d7e,1,a1beef8f3992dbd4cd8726796aa69c53,512d298ac2a96d1931b6bd30aa21f61d,2018-08-16 14:24:28,4399.87,113.45,4513.32
56663,80dfedb6d17bf23539beeef3c768f4d7,1,4ca7b91a31637bd24fb8e559d5e015e4,59417c56835dd8e2e72f91f809cd4092,2017-05-05 20:50:13,3999.00,195.76,4194.76
45843,68101694e5c5dc7330c91e1bbc36214f,1,6cdf8fc1d741c76586d8b6b15e9eef30,ed4acab38528488b65a9a9c603ff024a,2018-04-05 08:27:27,4099.99,75.27,4175.26
78310,b239ca7cd485940b31882363b52e6674,1,dd113cb02b2af9c8e5787e8f1f0722f6,821fb029fc6e495ca4f08a35d51e53a5,2018-08-02 08:15:14,4059.00,104.51,4163.51

In [21]:
df['freight_ratio'] = df['freight_value'] / df['price']

In [22]:
display(df.nlargest(10, 'freight_ratio'))

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total,freight_ratio
87081,c5bdd8ef3c0ec420232e668302179113,2,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-07 02:55:22,0.85,22.30,23.15,26.235294
27652,3ee6513ae7ea23bdfab5b9ab60bffcb5,1,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-04 03:55:26,0.85,18.23,19.08,21.447059
48625,6e864b3f0ec71031117ad4cf46b7f2a1,1,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-02 20:30:34,0.85,18.23,19.08,21.447059
110535,fb265b2dc558a56445dfc48f8224e201,1,baf25ed4f8f70238cc87230379471454,128f9bfbe4c7d5185033914b1de3d39a,2017-10-18 21:35:15,9.90,121.22,131.12,12.244444
94495,d642656598ae928a250620315d19e87e,1,b07fffe072c9adc235a35d8da7c0584d,dd533b429f380718b70ad9922c294bae,2018-03-13 10:55:37,4.99,37.04,42.03,7.422846
57297,8272b63d03f5f79c56e9e4120aec44ef,1,270516a3f41dc035aa87d220228f844c,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89,9.09,6.575000
57298,8272b63d03f5f79c56e9e4120aec44ef,2,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89,9.09,6.575000
57299,8272b63d03f5f79c56e9e4120aec44ef,3,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89,9.09,6.575000
57300,8272b63d03f5f79c56e9e4120aec44ef,4,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89,9.09,6.575000
57301,8272b63d03f5f79c56e9e4120aec44ef,5,05b515fdc76e888aada3c6d66c201dff,2709af9587499e95e803a6498a5a56e9,2017-07-21 18:25:23,1.20,7.89,9.09,6.575000

In [23]:
df['freight_ratio'].nlargest(10)

87081     26.235294
27652     21.447059
48625     21.447059
110535    12.244444
94495      7.422846
57297      6.575000
57298      6.575000
57299      6.575000
57300      6.575000
57301      6.575000
Name: freight_ratio, dtype: float64

In [24]:
weird = df[(df['price'] < 2) & (df['freight_value'] > 10)]
print(len(weird))
print(display(weird))

3

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total,freight_ratio
27652,3ee6513ae7ea23bdfab5b9ab60bffcb5,1,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-04 03:55:26,0.85,18.23,19.08,21.447059
48625,6e864b3f0ec71031117ad4cf46b7f2a1,1,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-02 20:30:34,0.85,18.23,19.08,21.447059
87081,c5bdd8ef3c0ec420232e668302179113,2,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-07 02:55:22,0.85,22.30,23.15,26.235294

None

In [25]:
extreme = df[df['freight_ratio'] > 10]

print("Extreme outliers:", len(extreme))
print(display(extreme))

Extreme outliers: 4

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total,freight_ratio
27652,3ee6513ae7ea23bdfab5b9ab60bffcb5,1,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-04 03:55:26,0.85,18.23,19.08,21.447059
48625,6e864b3f0ec71031117ad4cf46b7f2a1,1,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-02 20:30:34,0.85,18.23,19.08,21.447059
87081,c5bdd8ef3c0ec420232e668302179113,2,8a3254bee785a526d548a81a9bc3c9be,96804ea39d96eb908e7c3afdb671bb9e,2018-05-07 02:55:22,0.85,22.30,23.15,26.235294
110535,fb265b2dc558a56445dfc48f8224e201,1,baf25ed4f8f70238cc87230379471454,128f9bfbe4c7d5185033914b1de3d39a,2017-10-18 21:35:15,9.90,121.22,131.12,12.244444

None

In [26]:
df = df[df['freight_ratio'] <= 10]

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 112646 entries, 0 to 112649
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112646 non-null  object
 1   order_item_id        112646 non-null  int64
 2   product_id           112646 non-null  object
 3   seller_id            112646 non-null  object
 4   shipping_limit_date  112646 non-null  datetime64[ns]
 5   price                112646 non-null  float64
 6   freight_value        112646 non-null  float64
 7   item_total           112646 non-null  float64
 8   freight_ratio        112646 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(3)
memory usage: 8.6+ MB