In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
import sklearn

In [10]:
df = pd.read_csv('C:\\Users\\aviji\\Desktop\\capstone_project_1\\olist_order_payments_dataset.csv')

In [11]:
df.describe()
df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

np.int64(0)

In [12]:
display(df)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [13]:
df['order_id'].value_counts().head()

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
fedcd9f7ccdc8cba3a18defedd1a5547    19
Name: count, dtype: int64

In [14]:
df['payment_sequential'].unique()
df.groupby("order_id")["payment_sequential"].max().describe()

count    99440.000000
mean         1.045515
std          0.382177
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         29.000000
Name: payment_sequential, dtype: float64

In [15]:

df['payment_installments'].describe()
df['payment_installments'].value_counts().head()

payment_installments
1     52543
2     12413
3     10461
4      7098
10     5331
Name: count, dtype: int64

In [16]:
df['payment_type'].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [17]:
(df['payment_value'] <= 0).sum()
df[df['payment_value'] <= 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
19922,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0
43744,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
62674,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0
100766,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0

In [18]:
df['payment_value'].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [19]:
display(df['payment_value'].max())

13664.08

In [20]:
total_payment = df.groupby("order_id")['payment_value'].sum().reset_index()
display(total_payment)

                               order_id  payment_value
0      00010242fe8c5a6d1ba2dd792cb16214          72.19
1      00018f77f2f0320c557190d7a144bdd3         259.83
2      000229ec398224ef6ca0657da4fc703e         216.87
3      00024acbcdf0a6daa1e931b038114c75          25.78
4      00042b26cf59d7ce69dfabb4e55b4fd9         218.04
...                                 ...            ...
99435  fffc94f6ce00a00581880bf54a75a037         343.40
99436  fffcd46ef2263f404302a634eb57f7eb         386.53
99437  fffce4705a9662cd70adb13d4a31832d         116.85
99438  fffe18544ffabc95dfada21779c9644f          64.71
99439  fffe41c64501cc87c801fd61db3f6244          55.79

[99440 rows x 2 columns]

In [21]:
check = df.groupby("order_id")[["payment_value","payment_installments"]].max()
print(check)

                                  payment_value  payment_installments
order_id
00010242fe8c5a6d1ba2dd792cb16214          72.19                     2
00018f77f2f0320c557190d7a144bdd3         259.83                     3
000229ec398224ef6ca0657da4fc703e         216.87                     5
00024acbcdf0a6daa1e931b038114c75          25.78                     2
00042b26cf59d7ce69dfabb4e55b4fd9         218.04                     3
...                                         ...                   ...
fffc94f6ce00a00581880bf54a75a037         343.40                     1
fffcd46ef2263f404302a634eb57f7eb         386.53                     1
fffce4705a9662cd70adb13d4a31832d         116.85                     3
fffe18544ffabc95dfada21779c9644f          64.71                     3
fffe41c64501cc87c801fd61db3f6244          55.79                     1

[99440 rows x 2 columns]

In [22]:
df = df.drop_duplicates()

resolving

In [23]:
df = df[df['payment_sequential'] <= 12]

In [24]:
df = df[df['payment_installments'] <= 12]

In [25]:
df = df[~((df['payment_value'] == 0) & (df['payment_type'].isna()))]

In [26]:
df['payment_type'] = df['payment_type'].replace("not_defined", "unknown")

In [27]:
df[df['payment_value'] > 5000]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
34370,736e1922ae60d0d6a89247b851902527,1,boleto,1,7274.88
41419,0812eb902a67711a1cb742b3cdaa65ae,1,credit_card,8,6929.31
49581,fefacc66af859508bf1a7934eab1e97f,1,boleto,1,6922.21
52107,03caa2c082116e1d31e67e9ae3700499,1,credit_card,1,13664.08
62409,2cc9089445046817a7539d90805e6e5a,1,boleto,1,6081.54
85539,f5136e38d1a14a4dbd87dff67da82701,1,boleto,1,6726.66

In [28]:
display(df)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [29]:
# count before
print("before rows:", len(df), "exact sig-duplicates:",
      df.duplicated(subset=['order_id','payment_value']).sum())

# show some repeated signatures (sample)
print(df[df.duplicated(subset=['order_id','payment_value'], keep=False)].head(10))

# drop duplicates keeping first occurrence (in-place)
df = df.drop_duplicates(subset=['order_id','payment_value'], keep='first').reset_index(drop=True)

# count after
print("after rows:", len(df), "sig-duplicates left:",
      df.duplicated(subset=['order_id','payment_value']).sum())

# (optional) save cleaned payments
df.to_csv('cleaned_order_payments.csv', index=False)

before rows: 103624 exact sig-duplicates: 589
                              order_id  payment_sequential payment_type  \
121   ea9184ad433a404df1d72fa0a8764232                   4      voucher
181   591083bc42b589c7052118aa83118e76                   5      voucher
433   20aa4f85b1ed8d98e5c742c1a003db9c                   2      voucher
752   8ca5bdac5ebe8f2d6fc9171d5ebc906a                   3      voucher
783   4a686b47e7eecbd136617bf8ae7c9af4                   2      voucher
987   4fb76fa13b108a0d0478483421b0992c                   6      voucher
1117  6a0c96e8fd6d1c42bbfa1f5d49f3d3cb                   3      voucher
1200  53177d318c723e378c2a2aa1e9b2ea8e                   4      voucher
1222  a3a97bc6e236d5351537c8f466c34dad                   3      voucher
1312  59d02be1c50fb6e6930cafd6ff6a31e5                   7      voucher

      payment_installments  payment_value
121                      1          22.49
181                      1          20.00
433                      1          50.00
752                      1          15.00
783                      1          20.00
987                      1          10.04
1117                     1          64.25
1200                     1          20.00
1222                     1           6.67
1312                     1          20.00
after rows: 103035 sig-duplicates left: 0

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103035 entries, 0 to 103034
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103035 non-null  object
 1   payment_sequential    103035 non-null  int64
 2   payment_type          103035 non-null  object
 3   payment_installments  103035 non-null  int64
 4   payment_value         103035 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 3.9+ MB